version: "2.2"
services:
  jobmanager:
    build: ./
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager 
    volumes:
      - ./data:/tmp/iceberg/warehouse
      
  taskmanager:
    build: ./
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 20  
    volumes:
      - ./data:/tmp/iceberg/warehouse

  sql-client:
    build: ./
    command: bin/sql-client.sh
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager  
    volumes:
      - ./data:/tmp/iceberg/warehouse



